name: Docker

on:
  workflow_dispatch: {}
    
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
jobs:
  push-linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      IMAGE_OS: alpine
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag websocketproxy
      - name: Log into registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}:latest
          echo IMAGE_ID=${IMAGE_ID}
          docker tag websocketproxy ${IMAGE_ID}
          docker push ${IMAGE_ID}
